import { Vehicle } from '../types';

export const vehiclesData: Vehicle[] = [
  {
    id: 'force-traveller-17',
    name: 'Force Traveller 17 Seater',
    nameMr: 'फोर्स ट्रॅव्हलर १७ सीटर',
    category: 'traveller',
    seatingCapacity: 17,
    acAvailable: true,
    nonAcAvailable: true,
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=1200&auto=format&fit=crop',
    description: 'Luxury 17-seater minibus with reclining seats, ample luggage space, and comfortable suspension for long journeys.',
    descriptionMr: 'आरामदायी पुशबॅक सीट्स, मुबलक सामान ठेवण्याची जागा आणि लांब पल्ल्याच्या प्रवासासाठी उत्तम सस्पेंशनसह १७ सीटर लक्झरी ट्रॅव्हलर.',
    features: ['Pushback Seats', 'Ample Luggage Space', 'Music System', 'Charging Points', 'First Aid Kit'],
    featuresMr: ['पुशबॅक सीट्स', 'मुबलक सामानाची जागा', 'म्युझिक सिस्टीम', 'चार्जिंग पॉईंट्स', 'प्रथमोपचार पेटी'],
    idealFor: 'Family Outings, Pilgrimage & Corporate Tours',
    idealForMr: 'कौटुंबिक सहली, धार्मिक यात्रा व कॉर्पोरेट टूर',
  },
  {
    id: 'force-traveller-20',
    name: 'Force Traveller 20 Seater',
    nameMr: 'फोर्स ट्रॅव्हलर २० सीटर',
    category: 'traveller',
    seatingCapacity: 20,
    acAvailable: true,
    nonAcAvailable: true,
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=1200&auto=format&fit=crop',
    description: 'Spacious 20-seater luxury bus ideal for medium group excursions, wedding trips, and picnic tours.',
    descriptionMr: 'मध्यम आकाराच्या ग्रुप सहली, लग्नकार्याचे वऱ्हाड आणि पिकनिकसाठी उत्तम २० सीटर लक्झरी ट्रॅव्हलर.',
    features: ['Spacious Interiors', 'Reclining Seats', 'Powerful AC', 'Roof Luggage Carrier', 'Clean Curtains'],
    featuresMr: ['मोकळी बैठक व्यवस्था', 'पुशबॅक सीट्स', 'दमदार AC', 'रूफ करिअर', 'स्वच्छ पडदे'],
    idealFor: 'Wedding Events, Group Tours & Picnics',
    idealForMr: 'लग्न समारंभ, ग्रुप ट्रिप्स व पिकनिक',
  },
  {
    id: 'force-traveller-26',
    name: 'Force Traveller 26 Seater',
    nameMr: 'फोर्स ट्रॅव्हलर २६ सीटर',
    category: 'traveller',
    seatingCapacity: 26,
    acAvailable: true,
    nonAcAvailable: true,
    image: 'https://images.unsplash.com/photo-1562620669-98203f1938b8?q=80&w=1200&auto=format&fit=crop',
    description: 'Large capacity 26-seater minibus designed for heavy group tours, religious yatra packages, and large family trips.',
    descriptionMr: 'मोठ्या ग्रुप्स, धार्मिक तीर्थयात्रा आणि मोठ्या कुटुंबासाठी उत्तम २६ सीटर प्रशस्त ट्रॅव्हलर.',
    features: ['High Capacity', 'Individual Reading Lamps', 'Air Suspension', 'Large Boot Space', 'CCTV & Safety'],
    featuresMr: ['प्रशस्त २५+१ क्षमता', 'पुशबॅक सीट्स', 'एअर सस्पेंशन', 'मोठी डिग्गी', 'सुरक्षित प्रवास'],
    idealFor: 'Religious Yatra & Large Group Events',
    idealForMr: 'धार्मिक यात्रा व मोठ्या ग्रुपचे कार्यक्रम',
  },
  {
    id: 'force-cruiser-10',
    name: 'Force Cruiser 10 Seater',
    nameMr: 'फोर्स क्रूझर १० सीटर',
    category: 'cruiser',
    seatingCapacity: 10,
    acAvailable: true,
    nonAcAvailable: true,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=1200&auto=format&fit=crop',
    description: 'Sturdy 10-seater MUV suitable for rough terrains, village visits, pilgrimage tours, and budget travel.',
    descriptionMr: 'ग्रामीण भाग, डोंगराळ रस्ते आणि धार्मिक स्थळांच्या प्रवासासाठी अत्यंत दणकट १० सीटर क्रूझर.',
    features: ['Rugged Build', 'Comfortable Seating', 'High Ground Clearance', 'Carrier Available'],
    featuresMr: ['दणकट बॉडी', 'आरामदायी बैठक', 'उंच ग्राउंड क्लिअरन्स', 'वर करिअर सुविधा'],
    idealFor: 'Rural Travel, Pilgrimage & Budget Trips',
    idealForMr: 'ग्रामीण भाग प्रवास, देवदर्शन व बजेट ट्रिप्स',
  },
  {
    id: 'maruti-ertiga-7',
    name: 'Maruti Ertiga 7 Seater',
    nameMr: 'मारुती अर्टिगा ७ सीटर',
    category: 'car',
    seatingCapacity: 7,
    acAvailable: true,
    nonAcAvailable: false,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=1200&auto=format&fit=crop',
    description: 'Premium 7-seater MPV with plush interiors, dual AC, smooth suspension, perfect for small family trips and outstation rides.',
    descriptionMr: 'लहान कुटुंबासाठी अत्यंत आरामदायी आणि प्रीमियम ७ सीटर कार. ड्युअल AC सह स्मूथ राईड.',
    features: ['Dual AC', 'Plush Leatherette Seats', 'Smooth Ride', 'Bluetooth Audio', 'Silent Cabin'],
    featuresMr: ['ड्युअल AC', 'आरामदायी सीट्स', 'स्मूथ सस्पेंशन', 'म्युझिक सिस्टीम', 'सायलेंट केबिन'],
    idealFor: 'Small Family Trips & Outstation Travel',
    idealForMr: 'लहान कौटुंबिक सहली व आऊटस्टेशन टूर',
  },
  {
    id: 'maruti-eeco-7',
    name: 'Maruti Eeco 7 Seater',
    nameMr: 'मारुती ईको ७ सीटर',
    category: 'car',
    seatingCapacity: 7,
    acAvailable: true,
    nonAcAvailable: true,
    image: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?q=80&w=1200&auto=format&fit=crop',
    description: 'Economical 7-seater van providing reliable and affordable transportation for short trips, temple tours, and local travel.',
    descriptionMr: 'कमी खर्चात सुरक्षित आणि सोयीस्कर प्रवासासाठी उत्तम ७ सीटर मारुती ईको व्हेन.',
    features: ['Budget Friendly', 'Compact Yet Spacious', 'AC / Non-AC Option', 'Clean Interiors'],
    featuresMr: ['परवडणारा दर', 'प्रशस्त जागा', 'AC / Non-AC पर्याय', 'स्वच्छ गाडी'],
    idealFor: 'Short Distance Trips & Local Sightseeing',
    idealForMr: 'स्थानिक सहली, देवदर्शन व कमी अंतराचा प्रवास',
  },
  {
    id: 'maruti-dzire-4',
    name: 'Maruti Dzire 4 Seater',
    nameMr: 'मारुती डिझायर ४ सीटर',
    category: 'car',
    seatingCapacity: 4,
    acAvailable: true,
    nonAcAvailable: false,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1200&auto=format&fit=crop',
    description: 'Stylish 4-seater sedan offering high comfort, climate control AC, and quick travel for couples, corporate drop, or small groups.',
    descriptionMr: '४ प्रवाशांसाठी अत्यंत आरामदायी, ऑटोमॅटिक AC आणि प्रीमियम लुक असलेली सेडान कार.',
    features: ['Automatic Climate AC', 'Comfortable Legroom', 'Spacious Boot', 'Smooth Highway Drive'],
    featuresMr: ['ऑटोमॅटिक AC', 'उत्तम लेगरूम', 'प्रशस्त डिग्गी', 'वेगवान व सुरक्षित प्रवास'],
    idealFor: 'Airport Pick-Up/Drop, Business Trips & Couples',
    idealForMr: 'एयरपोर्ट पिकअप/ड्रॉप, कॉर्पोरेट टूर व सोलो/कपल ट्रिप',
  },
];
